name: 'GitHub Action for deleting a GitHub Release'
description: 'This is a GitHub Action for deleting a GitHub Release.'

branding:
  icon: delete
  color: 'blue'

inputs:
  owner:
    description: 'The owner of github'
    required: false
  repo:
    description: 'The repo of github'
    required: false
  release-name:
    description: 'The release name of github'
    required: false
  tag-name:
    description: 'The tag name of github'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
